# Generated by Django 5.2.7 on 2025-10-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='medicalLicenseNumber',
            new_name='medical_license_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userType',
            new_name='user_type',
        ),
    ]
