# Generated by Django 5.2.7 on 2025-10-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_medicallicensenumber_user_medical_license_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('P', 'Patient'), ('d', 'Doctor')], default='P', max_length=1),
        ),
    ]
