# Generated by Django 5.2.7 on 2025-10-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_license_number',
            field=models.CharField(default='n/a', max_length=50),
        ),
    ]
