# Generated by Django 5.2.7 on 2025-11-24 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood_entry',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
