# Generated by Django 5.2.7 on 2025-11-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mood', '0002_alter_mood_entry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mood_entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
    ]
