# Generated by Django 5.2.7 on 2025-11-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_patient_medication_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_medication',
            old_name='patient',
            new_name='user',
        ),
    ]
