# Generated by Django 5.2.7 on 2025-11-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_rename_patient_patient_medication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_medication',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('O', 'Other')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='patient_medication',
            name='reminder_type',
            field=models.CharField(choices=[('E', 'Email'), ('T', 'Text'), ('C', 'Call')], default='E', max_length=1),
        ),
    ]
