# Generated by Django 5.2.7 on 2025-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_patient_medication_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_medication',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Other', 'Other')], default='Daily', max_length=6),
        ),
        migrations.AlterField(
            model_name='patient_medication',
            name='reminder_type',
            field=models.CharField(choices=[('Email', 'Email'), ('Text', 'Text'), ('Call', 'Call')], default='Email', max_length=5),
        ),
    ]
